---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.


```{r}
library(tidyverse)
library(dplyr)
library(openintro)
library(leaflet)
library(ggplot2)
library(RColorBrewer)

starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
states_map <- map_data("state")

starbucks_us_by_state <- starbucks |>
  filter(Country == "US") |>
  count(State.Province) |>
  mutate(state_name = str_to_lower(abbr2state(State.Province)))

census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))

starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)



```


```{r}
#| fig-cap: "A Choroplethic Map of all Starbucks Locations in the Contiguous United States"
#| fig-alt: "This map plots every Starbucks within the 48 connected US states. Additionally, the color scale indicates the number of locations per 10,000 citizens by state. Looking at the map, we can see that western states such as California, Washington, Oregon, and Colorado contain the most Starbucks per capita. "

library(ggthemes)

starbucks_contiguous_us <- starbucks |>
  filter(Country == "US", State.Province != "AK", State.Province != "HI")

ggplot(starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = states_map) +
    geom_point(
    data = starbucks_contiguous_us,
    aes(x = Longitude , y = Latitude), 
    size = 0.05,
    alpha = 0.2,
    inherit.aes = FALSE
  ) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  theme_map() +
  labs(title = "A Choroplethic Map of all Starbucks Locations in the Contiguous United States") +
  labs(caption = "Created by Izzy Flood") +
  scale_fill_viridis_c()
```

