---
title: "ica-factors"
editor: visual
---

```{r}
library(tidyverse)
library(dplyr)

# Get rid of some duplicate rows!
grades <- read.csv("https://mac-stat.github.io/data/grades.csv") |> 
  distinct(sid, sessionID, .keep_all = TRUE)

# Check it out
head(grades)
```

```{r}
grade_distribution <- grades |> 
  count(grade)

head(grade_distribution)
```

```{r}
# Exercise 1

grade_distribution |> 
  ggplot(aes(x = grade, y = n)) +
    geom_col()

 grade_distribution |>
   mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
   ggplot(aes(x = grade, y = n)) +
     geom_col()
 
grade_distribution |>
   mutate(grade = fct_reorder(grade, n)) |>
   ggplot(aes(x = grade, y = n)) +
     geom_col()

grade_distribution |>
   mutate(grade = fct_reorder(grade, n, .desc = TRUE)) |>
   ggplot(aes(x = grade, y = n)) +
     geom_col()
grade_distribution |>
   mutate(grade = fct_infreq(grade, n)) |>
   ggplot(aes(x = grade, y = n)) +
     geom_col()
```

```{r}
# Exercise 2

grade_distribution |>
   mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
   mutate(grade = fct_recode(grade, "Satisfactory" = "S", "Audit" = "AU")) |>  
   ggplot(aes(x = grade, y = n)) +
     geom_col()
```
